# Generated by Django 6.0 on 2025-12-05 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demo_Col",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("col1", models.CharField()),
                ("col2", models.CharField(max_length=100)),
                ("col3", models.TextField()),
                ("col4", models.IntegerField()),
                ("col5", models.BigIntegerField()),
                ("col6", models.SmallIntegerField()),
                ("col7", models.FloatField()),
                ("col8", models.DecimalField(decimal_places=2, max_digits=5)),
                ("col9", models.SlugField(max_length=100)),
                ("col10", models.EmailField(max_length=100)),
                ("col11", models.URLField(max_length=100)),
                ("col12", models.UUIDField(default=uuid.uuid4)),
                ("col13", models.BooleanField(default=True)),
                ("col14", models.DateField(auto_now_add=True)),
                ("col15", models.TimeField(auto_now_add=True)),
                ("col16", models.DateTimeField(auto_now_add=True)),
                ("col17", models.DurationField()),
                ("col18", models.BinaryField()),
            ],
        ),
    ]
